services:
  - mysql
language: go
go:
  - 1.7
  - 1.8

sudo: false

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/vbatts/git-validation

install: true

env:
  - TESTCONN="testuser:testpass@tcp(localhost:3306)/testdb?charset=utf8"
script:
        #  - git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
  - ./mysql.sh
  - make
  - make test
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
